### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by jonathanrd** [samirelanduk/atomium#14]
Just spotted a documentation error, in the README you have an example containing:
```
>>> model.translate(34, -12, 3.5)
>>> model.rotate("x", 45)
>>> model.atom(element="O")
```

Unfortunately
`model.rotate("x", 45)`
returns:
`ValueError: 45 is not a valid axis`

Switching the order to:
`model.rotate(45, "x")`
runs as expected though.

Great work on atomium, really simple to integrate within other scripts.. cheers!

**Comment by samirelanduk** [comment]
Good catch - have fixed in the 0.10 branch.

And cheers! (:
