### ISSUE TITLE
Create conda package as well as pypi

### ISSUE THREAD

**Issue by samirelanduk** [samirelanduk/atomium#21]

**Comment by jaimergp** [comment]
I'd be happy to contribute a recipe for conda-forge!

**Comment by samirelanduk** [comment]
Oh if you can help that would be great! I don't really use anaconda so I'm not sure what the procedure is for publishing to it.

**Comment by jaimergp** [comment]
Check https://github.com/conda-forge/staged-recipes/pull/10945!

**Comment by jaimergp** [comment]
There you go! https://anaconda.org/conda-forge/atomium

As a by product, `[valerius](https://anaconda.org/conda-forge/valerius)` also got its conda package :)

**Comment by samirelanduk** [comment]
Great! Thanks so much - I'll let people know about this tomorrow.
