### ISSUE TITLE
Zero-pad pdb temperature factor

### ISSUE THREAD

**Issue by hippolytej** [samirelanduk/atomium#32]
### For Bug Reports

Hi, it seems that when saving a structure to PDB format, the temperature factor does not get zero padded correctly, e.g.:

```
ATOM    194  O   LYS A  20      34.379  53.562  37.179  1.00 53.10           O  # expected
ATOM    194  O   LYS A  20      34.379  53.562  37.179  1.00  53.1           O  # actual
```

#### Example code to reproduce

``` python
import atomium

model = atomium.fetch("5LXR").model
print((atomium.pdb.structure_to_pdb_string((model.residue("A.7"))).split("\n")[4]))
````

#### Python Version/Operating System

Python 3.7.7, Macos, atomium v1.0.8

**Comment by samirelanduk** [comment]
Thanks for spotting this, it should be fixed now. I'll add it to PyPI as 1.0.9 in the next few days.
