### ISSUE TITLE
getting the residue details from an atom

### ISSUE THREAD

**Issue by rbf22** [samirelanduk/atomium#33]
it would be great if while iterating over nearby atoms it was possible to access the chain and residues for these atoms. Is there a way to do this?

for example:
```
for atom_i in model.atoms():
  for atom_j in atom_i.nearby(6.):
    print(atom_j.chain, atom_j.residue_name, atom_j.residue_number)
```

**Comment by samirelanduk** [comment]
The following works for me:

```python
for atom_i in model.atoms():
    for atom_j in atom_i.nearby_atoms(6.):
        print(atom_j.chain, atom_j.het.name, atom_j.het.id.split(".")[1])
```

The residue number is a bit convoluted because residue's currently just have an ID of the form A123 - I think I should make the number a separate property in future.

**Comment by rbf22** [comment]
Is there a way to get the residue type, i.e. THR, SER etc?

**Comment by samirelanduk** [comment]
`atom_j.het.name` returns the residue type.
