### ISSUE TITLE
the "add_secondary_structure_to_polymers" function in the mmcif.py module only recognises single-letter chain identifiers

### ISSUE THREAD

**Issue by FunkTipp** [samirelanduk/atomium#34]
### For Bug Reports
the "add_secondary_structure_to_polymers" function in the mmcif.py module only recognises single-letter chain identifiers

#### Problem
cryoEM derived mmcif files often have multi-litter chain identifiers, those chains are not recognised and secondary structure information is not forwarded to downstream functions

the reason can be found in line 567:
`<chain = model["polymer"].get(segment[0][0])>`
it should be exchanged by:
`<chain = model["polymer"].get(segment[0].split('.')[0])>`
or similar behaving commands to allow multi-letter chain identifiers

#### Python Version/Operating System
atomimuim 1.0.6

**Comment by samirelanduk** [comment]
Thanks for spotting this - I'll publish a fix this week.

**Comment by samirelanduk** [comment]
This should be fixed now in 1.0.10 (just released).
